Clickable asset links
Fair-Share-Group/fairsite pull request #8
Opened 2023-02-02 11:57 UTC by yhpc

- all asset types will now open non-empty urls, no url validation at this stage
- all asset types will now show URL in widget

2023-02-04 02:42 UTC, kovarny requested changes

2023-02-04 02:42 UTC, kovarny commented on lib/common.dart
> +Future<void> openUrl(String url, BuildContext context) async {
Don't think Future<void> is necessary.

2023-02-04 02:42 UTC, kovarny commented on lib/company/asset/abn_asset_widget.dart
> +              onTap: () => openUrl((assetDoc.data()?['url'] ?? ''), context), // in the future, can probably get rid of null handling
Shouldn't be storing URL in ABN firstore doc. It should store just  the ABN.

2023-02-04 02:42 UTC, kovarny commented on lib/company/asset/facebook_asset_widget.dart
> +      title: Text('Facebook - ${assetDoc.data()?["url"]}'),
Suggest we store ID s not the URLS

2023-02-05 11:06 UTC, yhpc commented on lib/company/asset/abn_asset_widget.dart
> +              onTap: () => openUrl((assetDoc.data()?['url'] ?? ''), context), // in the future, can probably get rid of null handling
Done in "Refacotr & Bug Fix"

2023-02-05 11:06 UTC, yhpc commented on lib/company/asset/facebook_asset_widget.dart
> +      title: Text('Facebook - ${assetDoc.data()?["url"]}'),
Done in "Refacotr & Bug Fix"

2023-02-07 02:08 UTC, kovarny approved these changes

2023-02-07 02:08 UTC, merged